enum Steps {
  USER_REGISTER = "USER_REGISTER",
  SET_PASSWORD = "SET_PASSWORD",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  ACCOUNT_LINKING = "ACCOUNT_LINKING",
  SETUP_PASSWORD = "SETUP_PASSWORD",
  EMAIL_LOGIN_NOT_AVAILABLE = 'EMAIL_LOGIN_NOT_AVAILABLE',
}

export default Steps;
