import { DocumentFilledIcon } from "../svgs/svg";
import { EChatTypes, EModels } from "../enums/modals.enum";

export const SuggestionData = {
  [EModels.GPT_3]: [
    { heading: "Quick Problem Solving", question: "Can you help me break down this complex problem into manageable steps?", icon: <DocumentFilledIcon />, },
    { heading: "Explanation Clarity", question: "Explain the concept of quantum computing in simple terms.", icon: <DocumentFilledIcon /> },
    { heading: "Brainstorming Aid", question: "Generate 5 unique business ideas for a sustainable tech startup.", icon: <DocumentFilledIcon /> },
    { heading: "Writing Assistance", question: "Help me draft a professional email to my project manager.", icon: <DocumentFilledIcon /> },
    { heading: "Basic Coding Help", question: "Provide a Python script to calculate Fibonacci sequence.", icon: <DocumentFilledIcon /> },
    { heading: "Language Translation", question: "Translate this English paragraph to Spanish.", icon: <DocumentFilledIcon /> },
    { heading: "Math Problem Solving", question: "Walk me through solving this algebraic equation.", icon: <DocumentFilledIcon /> },
    { heading: "General Knowledge Quiz", question: "Test my knowledge on world history.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Writing Prompt", question: "Help me start a short story about unexpected adventure.", icon: <DocumentFilledIcon /> },
    { heading: "Basic Research Summary", question: "Summarize the key points of climate change research.", icon: <DocumentFilledIcon /> },
    { heading: "Recipe Development", question: "Suggest a healthy dinner recipe with these ingredients.", icon: <DocumentFilledIcon /> },
    { heading: "Simple Data Analysis", question: "Help me interpret these basic statistical trends.", icon: <DocumentFilledIcon /> },
    { heading: "Study Guide Creation", question: "Create a study outline for high school biology.", icon: <DocumentFilledIcon /> },
    { heading: "Travel Planning", question: "Recommend a 3-day itinerary for Paris.", icon: <DocumentFilledIcon /> },
    { heading: "Personal Productivity", question: "Suggest time management techniques for students.", icon: <DocumentFilledIcon /> },
    { heading: "Basic Financial Advice", question: "Explain compound interest for beginners.", icon: <DocumentFilledIcon /> },
    { heading: "Grammar Check", question: "Review and correct this paragraph for grammar.", icon: <DocumentFilledIcon /> },
    { heading: "Career Guidance", question: "Provide tips for a successful job interview.", icon: <DocumentFilledIcon /> },
    { heading: "Science Explanation", question: "Describe how photosynthesis works.", icon: <DocumentFilledIcon /> },
    { heading: "Goal Setting", question: "Help me create SMART goals for personal development.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.GPT_4]: [
    { heading: "Advanced Problem Decomposition", question: "Analyze this complex system architecture and suggest optimization strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Deep Creative Writing", question: "Develop a sophisticated narrative with multilayered character development.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Report Drafting", question: "Compose a comprehensive research paper outline on AI ethics.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Data Interpretation", question: "Provide in-depth analysis of these intricate economic indicators.", icon: <DocumentFilledIcon /> },
    { heading: "Nuanced Coding Solution", question: "Design an advanced algorithm for machine learning prediction.", icon: <DocumentFilledIcon /> },
    { heading: "Philosophical Discourse", question: "Explore the ethical implications of artificial consciousness.", icon: <DocumentFilledIcon /> },
    { heading: "Interdisciplinary Research", question: "Connect insights from psychology, neuroscience, and technology.", icon: <DocumentFilledIcon /> },
    { heading: "Strategic Business Planning", question: "Develop a detailed 5-year business expansion strategy.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Scientific Modeling", question: "Create a predictive model for climate change scenarios.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Innovation", question: "Generate breakthrough ideas for sustainable urban development.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Policy Analysis", question: "Evaluate multilateral approaches to global challenges.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Writing Critique", question: "Provide deep literary analysis and stylistic feedback.", icon: <DocumentFilledIcon /> },
    { heading: "Complex System Design", question: "Architect a scalable cloud infrastructure solution.", icon: <DocumentFilledIcon /> },
    { heading: "Hypothetical Scenario Planning", question: "Model potential geopolitical shifts in the next decade.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Financial Modeling", question: "Develop sophisticated investment strategy frameworks.", icon: <DocumentFilledIcon /> },
    { heading: "Cross-Cultural Communication", question: "Analyze communication nuances in international business.", icon: <DocumentFilledIcon /> },
    { heading: "Technological Trend Forecasting", question: "Predict emerging technologies and their societal impact.", icon: <DocumentFilledIcon /> },
    { heading: "Ethical AI Development", question: "Design guidelines for responsible AI implementation.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Healthcare Analysis", question: "Explore integrated approaches to global health challenges.", icon: <DocumentFilledIcon /> },
    { heading: "Future Scenario Simulation", question: "Construct detailed future scenario models across various domains.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.CLAUDE]: [
    { heading: "Ethical Reasoning", question: "Analyze the ethical dimensions of a complex moral dilemma.", icon: <DocumentFilledIcon /> },
    { heading: "Precise Technical Writing", question: "Draft a comprehensive technical documentation outline.", icon: <DocumentFilledIcon /> },
    { heading: "Nuanced Argument Construction", question: "Develop a balanced perspective on a controversial topic.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Problem Solving", question: "Break down a multifaceted organizational challenge.", icon: <DocumentFilledIcon /> },
    { heading: "Sophisticated Research Synthesis", question: "Integrate insights from multiple academic disciplines.", icon: <DocumentFilledIcon /> },
    { heading: "Contextual Language Analysis", question: "Provide deep linguistic and contextual text interpretation.", icon: <DocumentFilledIcon /> },
    { heading: "Systematic Approach Development", question: "Create a strategic framework for innovation management.", icon: <DocumentFilledIcon /> },
    { heading: "Critical Thinking Exercise", question: "Deconstruct an argument's logical structure and potential fallacies.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Policy Evaluation", question: "Analyze policy implications from multiple perspectives.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Communication Strategy", question: "Develop a nuanced communication plan for complex scenarios.", icon: <DocumentFilledIcon /> },
    { heading: "Interdisciplinary Knowledge Integration", question: "Connect insights across different academic fields.", icon: <DocumentFilledIcon /> },
    { heading: "Detailed Scenario Planning", question: "Construct comprehensive future scenario models.", icon: <DocumentFilledIcon /> },
    { heading: "Philosophical Concept Exploration", question: "Discuss complex philosophical ideas with depth and clarity.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Writing Refinement", question: "Provide sophisticated editorial feedback on academic writing.", icon: <DocumentFilledIcon /> },
    { heading: "Strategic Decision-Making Framework", question: "Design a comprehensive decision-making approach.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Systems Analysis", question: "Evaluate intricate organizational or technological ecosystems.", icon: <DocumentFilledIcon /> },
    { heading: "Ethical Leadership Guidance", question: "Develop principles for principled leadership in challenging environments.", icon: <DocumentFilledIcon /> },
    { heading: "Academic Research Methodology", question: "Design a rigorous research approach for complex studies.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Risk Assessment", question: "Analyze potential risks and mitigation strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Intellectual Discourse", question: "Engage in deep, nuanced exploration of abstract concepts.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.GEMINI]: [
    { heading: "Multimodal Data Processing", question: "Analyze and synthesize information from diverse data sources.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Research Integration", question: "Combine insights from multiple research domains.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Task Decomposition", question: "Break down and solve multifaceted problems efficiently.", icon: <DocumentFilledIcon /> },
    { heading: "Cross-Language Knowledge Transfer", question: "Translate and adapt complex concepts across languages.", icon: <DocumentFilledIcon /> },
    { heading: "Sophisticated Content Generation", question: "Create comprehensive, context-aware content.", icon: <DocumentFilledIcon /> },
    { heading: "Adaptive Learning Strategy", question: "Develop personalized learning approaches.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Data Visualization", question: "Design advanced data representation methods.", icon: <DocumentFilledIcon /> },
    { heading: "Interdisciplinary Problem Solving", question: "Connect solutions across different fields.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Simulation Modeling", question: "Create complex predictive models.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Multimodal Content Creation", question: "Generate rich, interactive multimedia content.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Relationship Analysis", question: "Explore intricate interdependencies in data.", icon: <DocumentFilledIcon /> },
    { heading: "High-Level Ethical Analysis", question: "Delve into nuanced ethical and social issues.", icon: <DocumentFilledIcon /> },
    { heading: "Strategic Vision Development", question: "Construct comprehensive long-term strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Risk Scenario Planning", question: "Develop robust approaches to risk and uncertainty.", icon: <DocumentFilledIcon /> },
    { heading: "Intelligent Workflow Automation", question: "Optimize processes using AI-driven solutions.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Thought Experimentation", question: "Engage in high-level intellectual exploration.", icon: <DocumentFilledIcon /> },
    { heading: "Expert Knowledge Representation", question: "Develop intricate knowledge models.", icon: <DocumentFilledIcon /> },
    { heading: "Sophisticated Data Integration", question: "Combine and analyze complex datasets.", icon: <DocumentFilledIcon /> },
    { heading: "Future Tech Exploration", question: "Dive deep into the implications of emerging technologies.", icon: <DocumentFilledIcon /> },
    { heading: "Global Knowledge Frameworks", question: "Explore universal frameworks for understanding complex systems.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.LLAMA]: [
    { heading: "Efficient Problem Solving", question: "Break down technical challenges quickly and precisely.", icon: <DocumentFilledIcon /> },
    { heading: "Concise Technical Explanation", question: "Provide clear, detailed explanations of complex concepts.", icon: <DocumentFilledIcon /> },
    { heading: "Rapid Coding Assistance", question: "Generate efficient code solutions for programming challenges.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Documentation", question: "Create precise and comprehensive technical documentation.", icon: <DocumentFilledIcon /> },
    { heading: "Data Analysis Approach", question: "Develop systematic methods for data interpretation.", icon: <DocumentFilledIcon /> },
    { heading: "Algorithm Design", question: "Create efficient algorithmic solutions for computational problems.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Research Summary", question: "Condense complex technical research into clear summaries.", icon: <DocumentFilledIcon /> },
    { heading: "Performance Optimization", question: "Provide strategies for system and code performance improvement.", icon: <DocumentFilledIcon /> },
    { heading: "Quick Learning Resources", question: "Generate targeted learning paths for technical skills.", icon: <DocumentFilledIcon /> },
    { heading: "Practical Problem Solving", question: "Offer pragmatic solutions to technical challenges.", icon: <DocumentFilledIcon /> },
    { heading: "Coding Best Practices", question: "Explain and demonstrate coding standards and best practices.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Trend Analysis", question: "Provide insights into emerging technological trends.", icon: <DocumentFilledIcon /> },
    { heading: "Efficient Debugging Strategies", question: "Develop systematic approaches to code debugging.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Communication", question: "Create clear, precise technical communication materials.", icon: <DocumentFilledIcon /> },
    { heading: "System Architecture Review", question: "Analyze and suggest improvements for technical architectures.", icon: <DocumentFilledIcon /> },
    { heading: "Quick Prototype Development", question: "Generate rapid prototype solutions for technical challenges.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Skill Assessment", question: "Design comprehensive technical skill evaluation methods.", icon: <DocumentFilledIcon /> },
    { heading: "Efficient Resource Management", question: "Provide strategies for optimal resource utilization.", icon: <DocumentFilledIcon /> },
    { heading: "Technical Innovation Approach", question: "Generate innovative solutions to technical problems.", icon: <DocumentFilledIcon /> },
    { heading: "Rapid Learning Methodology", question: "Design efficient learning strategies for technical domains.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.DOLPHIN]: [
    { heading: "Uncensored Creative Exploration", question: "Generate unrestricted creative content and ideas.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Coding Challenges", question: "Solve complex programming problems with detailed explanations.", icon: <DocumentFilledIcon /> },
    { heading: "Open-Ended Problem Solving", question: "Approach challenges without predefined constraints.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Technical Deep Dive", question: "Provide in-depth technical analysis and insights.", icon: <DocumentFilledIcon /> },
    { heading: "Innovative Solution Generation", question: "Create unique approaches to complex problems.", icon: <DocumentFilledIcon /> },
    { heading: "Detailed Coding Support", question: "Offer comprehensive coding assistance and implementation.", icon: <DocumentFilledIcon /> },
    { heading: "Unrestricted Brainstorming", question: "Generate creative ideas without typical AI limitations.", icon: <DocumentFilledIcon /> },
    { heading: "Complex System Design", question: "Architect sophisticated technological solutions.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Technical Modeling", question: "Develop intricate technical and computational models.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Research Exploration", question: "Conduct deep, unrestricted research analysis.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Coding Techniques", question: "Explore innovative programming approaches.", icon: <DocumentFilledIcon /> },
    { heading: "Detailed Technological Simulation", question: "Create comprehensive simulative models.", icon: <DocumentFilledIcon /> },
    { heading: "Unfiltered Intellectual Discourse", question: "Engage in open, unrestricted intellectual exploration.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Problem Decomposition", question: "Break down complex challenges comprehensively.", icon: <DocumentFilledIcon /> },
    { heading: "Innovative Technical Strategy", question: "Develop cutting-edge technological strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Deep Learning Exploration", question: "Investigate advanced machine learning concepts.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Performance Analysis", question: "Provide detailed system and performance evaluations.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Solution Engineering", question: "Generate innovative solutions across domains.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Theoretical Modeling", question: "Develop sophisticated theoretical frameworks.", icon: <DocumentFilledIcon /> },
    { heading: "Unrestricted Conceptual Exploration", question: "Dive deep into complex, nuanced concepts.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.DEEPSEEK]: [
    { heading: "Reasoning Walkthrough", question: "Think step-by-step and explain your reasoning for solving this logic puzzle.", icon: <DocumentFilledIcon /> },
    { heading: "Code Reasoning", question: "Read this function and explain potential edge cases and how to fix them.", icon: <DocumentFilledIcon /> },
    { heading: "Math Derivation", question: "Solve this math problem and show each derivation step clearly.", icon: <DocumentFilledIcon /> },
    { heading: "Error Tracing", question: "Given this stack trace, identify the root cause and propose a minimal fix.", icon: <DocumentFilledIcon /> },
    { heading: "Algorithm Design", question: "Design an efficient algorithm for this problem and justify the time/space complexity.", icon: <DocumentFilledIcon /> },
    { heading: "Explain Your Plan", question: "Outline a plan before answering and then execute it to answer the question.", icon: <DocumentFilledIcon /> },
    { heading: "Refactor for Clarity", question: "Refactor this code to improve readability while preserving behavior.", icon: <DocumentFilledIcon /> },
    { heading: "Unit Tests", question: "Write unit tests that capture tricky edge cases for this module.", icon: <DocumentFilledIcon /> },
    { heading: "Compare Approaches", question: "Compare two solution approaches and explain when to prefer each.", icon: <DocumentFilledIcon /> },
    { heading: "Translate Reasoning", question: "Translate this explanation into plain language for a non-technical audience.", icon: <DocumentFilledIcon /> },
    { heading: "Data Structures", question: "Choose the right data structure for this scenario and justify the choice.", icon: <DocumentFilledIcon /> },
    { heading: "Bug Reproduction", question: "Create a minimal reproducible example for this reported bug.", icon: <DocumentFilledIcon /> },
    { heading: "Optimization", question: "Identify performance bottlenecks and propose measurable optimizations.", icon: <DocumentFilledIcon /> },
    { heading: "Explain a Proof", question: "Present an outline proof for this statement and discuss assumptions.", icon: <DocumentFilledIcon /> },
    { heading: "Chain-of-Thought", question: "Provide a careful chain-of-thought for this complex reasoning task.", icon: <DocumentFilledIcon /> },
  ],
  [EModels.GROK]: [
    { heading: "Current Events", question: "Give a witty but informative summary of today's top tech news.", icon: <DocumentFilledIcon /> },
    { heading: "Humorous Insight", question: "Explain quantum computing like I'm five—with tasteful humor.", icon: <DocumentFilledIcon /> },
    { heading: "Trend Analysis", question: "What topics are trending in AI this week and why do they matter?", icon: <DocumentFilledIcon /> },
    { heading: "Debate Prep", question: "Prepare a snappy argument for and against open-source AI models.", icon: <DocumentFilledIcon /> },
    { heading: "Startup Advice", question: "Give unconventional advice for launching a developer tool startup.", icon: <DocumentFilledIcon /> },
    { heading: "Explain Like X", question: "Explain LLM context windows using sports metaphors.", icon: <DocumentFilledIcon /> },
    { heading: "Bug Roast", question: "Roast this bug report, then seriously suggest the fix.", icon: <DocumentFilledIcon /> },
    { heading: "API Guide", question: "Draft a concise API quickstart with examples and pitfalls.", icon: <DocumentFilledIcon /> },
    { heading: "Product Teardown", question: "Do a playful teardown of this product and propose improvements.", icon: <DocumentFilledIcon /> },
    { heading: "Research Recap", question: "Summarize a recent AI paper with key takeaways and zingers.", icon: <DocumentFilledIcon /> },
    { heading: "Coding Challenge", question: "Solve this coding challenge and explain the trick behind it.", icon: <DocumentFilledIcon /> },
    { heading: "Prompt Remix", question: "Rewrite this prompt to be sharper, shorter, and more effective.", icon: <DocumentFilledIcon /> },
    { heading: "Security Check", question: "Point out security gotchas in this snippet and suggest mitigations.", icon: <DocumentFilledIcon /> },
    { heading: "Release Notes", question: "Draft tongue-in-cheek yet clear release notes for this feature.", icon: <DocumentFilledIcon /> },
    { heading: "Marketing Hook", question: "Write three edgy taglines for a privacy-first AI assistant.", icon: <DocumentFilledIcon /> },
  ],
  [EChatTypes.SMART_LLM]: [
    { heading: "Technical Troubleshooting", question: "Diagnose and resolve complex technical issues in software and hardware.", icon: <DocumentFilledIcon /> },
    { heading: "Academic Research Assistance", question: "Support in conducting thorough academic research and literature reviews.", icon: <DocumentFilledIcon /> },
    { heading: "Financial Analysis and Strategy", question: "Provide insights on financial planning and investment strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Medical Knowledge Exploration", question: "Discuss recent advancements in health and medical research.", icon: <DocumentFilledIcon /> },
    { heading: "Legal Case Analysis", question: "Analyze legal cases and provide insights on potential outcomes.", icon: <DocumentFilledIcon /> },
    { heading: "Creative Writing Prompts", question: "Generate unique prompts for creative writing exercises.", icon: <DocumentFilledIcon /> },
    { heading: "Film and Literature Critique", question: "Offer critiques and analyses of films and literary works.", icon: <DocumentFilledIcon /> },
    { heading: "Travel Planning Insights", question: "Assist in planning travel itineraries and exploring new destinations.", icon: <DocumentFilledIcon /> },
    { heading: "Personal Development Strategies", question: "Suggest methods for personal growth and self-improvement.", icon: <DocumentFilledIcon /> },
    { heading: "Gadget Reviews and Recommendations", question: "Review and recommend the latest technology gadgets.", icon: <DocumentFilledIcon /> },
    { heading: "Sustainability Practices", question: "Explore effective practices for environmental sustainability.", icon: <DocumentFilledIcon /> },
    { heading: "Sports Analysis and Commentary", question: "Provide analysis and commentary on recent sports events.", icon: <DocumentFilledIcon /> },
    { heading: "Culinary Techniques and Recipes", question: "Share innovative cooking techniques and recipes.", icon: <DocumentFilledIcon /> },
    { heading: "Educational Curriculum Development", question: "Assist in developing comprehensive educational curricula.", icon: <DocumentFilledIcon /> },
    { heading: "Business Innovation Strategies", question: "Generate ideas for innovative business practices and models.", icon: <DocumentFilledIcon /> },
    { heading: "Health and Wellness Guidance", question: "Provide advice on maintaining a healthy lifestyle.", icon: <DocumentFilledIcon /> },
    { heading: "Legal Compliance and Regulations", question: "Explain important legal compliance issues for businesses.", icon: <DocumentFilledIcon /> },
    { heading: "Artistic Techniques and Styles", question: "Explore various artistic techniques and styles in visual arts.", icon: <DocumentFilledIcon /> },
    { heading: "Geographical Insights and Trends", question: "Discuss current trends in geography and global studies.", icon: <DocumentFilledIcon /> },
    { heading: "Daily Life Hacks", question: "Share practical tips for improving daily life efficiency.", icon: <DocumentFilledIcon /> }
  ],

  [EModels.ELIJAH]: [
    { heading: "Ethical Reasoning", question: "Analyze the ethical dimensions of a complex moral dilemma.", icon: <DocumentFilledIcon /> },
    { heading: "Precise Technical Writing", question: "Draft a comprehensive technical documentation outline.", icon: <DocumentFilledIcon /> },
    { heading: "Nuanced Argument Construction", question: "Develop a balanced perspective on a controversial topic.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Problem Solving", question: "Break down a multifaceted organizational challenge.", icon: <DocumentFilledIcon /> },
    { heading: "Sophisticated Research Synthesis", question: "Integrate insights from multiple academic disciplines.", icon: <DocumentFilledIcon /> },
    { heading: "Contextual Language Analysis", question: "Provide deep linguistic and contextual text interpretation.", icon: <DocumentFilledIcon /> },
    { heading: "Systematic Approach Development", question: "Create a strategic framework for innovation management.", icon: <DocumentFilledIcon /> },
    { heading: "Critical Thinking Exercise", question: "Deconstruct an argument's logical structure and potential fallacies.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Policy Evaluation", question: "Analyze policy implications from multiple perspectives.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Communication Strategy", question: "Develop a nuanced communication plan for complex scenarios.", icon: <DocumentFilledIcon /> },
    { heading: "Interdisciplinary Knowledge Integration", question: "Connect insights across different academic fields.", icon: <DocumentFilledIcon /> },
    { heading: "Detailed Scenario Planning", question: "Construct comprehensive future scenario models.", icon: <DocumentFilledIcon /> },
    { heading: "Philosophical Concept Exploration", question: "Discuss complex philosophical ideas with depth and clarity.", icon: <DocumentFilledIcon /> },
    { heading: "Advanced Writing Refinement", question: "Provide sophisticated editorial feedback on academic writing.", icon: <DocumentFilledIcon /> },
    { heading: "Strategic Decision-Making Framework", question: "Design a comprehensive decision-making approach.", icon: <DocumentFilledIcon /> },
    { heading: "Complex Systems Analysis", question: "Evaluate intricate organizational or technological ecosystems.", icon: <DocumentFilledIcon /> },
    { heading: "Ethical Leadership Guidance", question: "Develop principles for principled leadership in challenging environments.", icon: <DocumentFilledIcon /> },
    { heading: "Academic Research Methodology", question: "Design a rigorous research approach for complex studies.", icon: <DocumentFilledIcon /> },
    { heading: "Comprehensive Risk Assessment", question: "Analyze potential risks and mitigation strategies.", icon: <DocumentFilledIcon /> },
    { heading: "Intellectual Discourse", question: "Engage in deep, nuanced exploration of abstract concepts.", icon: <DocumentFilledIcon /> },
  ],
};




